/**
 * CampusPulse Embedded Database
 * This file allows the dashboard to run without a local server by bypassing CORS.
 */
window.CAMPUS_DB = [
    { "Name": "Suresh Singh", "Facility": "CSE Lab", "Rating": 5, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Mechanical Eng", "Year": "2nd Year", "Date": "2025-12-25" },
    { "Name": "Sonal Verma", "Facility": "CSE Lab", "Rating": 3, "Comment": "Sports center gets a bit crowded.", "Department": "Civil Eng", "Year": "2nd Year", "Date": "2025-08-30" },
    { "Name": "Sanjay Rao", "Facility": "CSE Lab", "Rating": 3, "Comment": "Sports center gets a bit crowded.", "Department": "Civil Eng", "Year": "3rd Year", "Date": "2025-12-22" },
    { "Name": "Aditi Nair", "Facility": "Library", "Rating": 3, "Comment": "Could be better.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-09-14" },
    { "Name": "Ritu Sharma", "Facility": "Auditorium", "Rating": 3, "Comment": "Average experience at the cafeteria.", "Department": "Business Admin", "Year": "4th Year", "Date": "2025-11-06" },
    { "Name": "Ishani Verma", "Facility": "Sports Center", "Rating": 4, "Comment": "High-speed internet is a life saver.", "Department": "Electronics", "Year": "4th Year", "Date": "2025-08-27" },
    { "Name": "Rahul Rao", "Facility": "Library", "Rating": 5, "Comment": "CSE Lab equipment is top notch.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-11-09" },
    { "Name": "Sonal Gupta", "Facility": "Cafeteria", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-08-23" },
    { "Name": "Anjali Singh", "Facility": "CSE Lab", "Rating": 3, "Comment": "Decent internet speeds.", "Department": "Electronics", "Year": "1st Year", "Date": "2025-10-27" },
    { "Name": "Arjun Gupta", "Facility": "CSE Lab", "Rating": 5, "Comment": "High-speed internet is a life saver.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-09-25" },
    { "Name": "Karthik Singh", "Facility": "IT Center", "Rating": 3, "Comment": "Could be better.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-08-30" },
    { "Name": "Rohan Iyer", "Facility": "IT Center", "Rating": 5, "Comment": "Sports center is well maintained.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-18" },
    { "Name": "Priya Iyer", "Facility": "Cafeteria", "Rating": 3, "Comment": "Average labs.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-10-28" },
    { "Name": "Karthik Chauhan", "Facility": "Cafeteria", "Rating": 1, "Comment": "Wait times at cafeteria are too high.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-08-06" },
    { "Name": "Rahul Iyer", "Facility": "Library", "Rating": 4, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-09-21" },
    { "Name": "Suresh Patel", "Facility": "CSE Lab", "Rating": 5, "Comment": "High-speed internet is a life saver.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-12-17" },
    { "Name": "Rohan Verma", "Facility": "Sports Center", "Rating": 5, "Comment": "CSE Lab equipment is top notch.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-09-06" },
    { "Name": "Rahul Patel", "Facility": "CSE Lab", "Rating": 5, "Comment": "Sports center is well maintained.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-09-29" },
    { "Name": "Karthik Iyer", "Facility": "IT Center", "Rating": 4, "Comment": "CSE Lab equipment is top notch.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-08-22" },
    { "Name": "Manish Gupta", "Facility": "Library", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Mechanical Eng", "Year": "3rd Year", "Date": "2025-12-15" },
    { "Name": "Rahul Chauhan", "Facility": "Auditorium", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Mechanical Eng", "Year": "4th Year", "Date": "2025-10-10" },
    { "Name": "Aditi Chauhan", "Facility": "Sports Center", "Rating": 5, "Comment": "Library has a great collection of research papers.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-12-14" },
    { "Name": "Suresh Reddy", "Facility": "Cafeteria", "Rating": 4, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-09-13" },
    { "Name": "Amit Gupta", "Facility": "Auditorium", "Rating": 5, "Comment": "Library has a great collection of research papers.", "Department": "Electronics", "Year": "3rd Year", "Date": "2025-10-18" },
    { "Name": "Neha Iyer", "Facility": "Cafeteria", "Rating": 3, "Comment": "Average labs.", "Department": "Electronics", "Year": "1st Year", "Date": "2025-08-18" },
    { "Name": "Aditi Reddy", "Facility": "Sports Center", "Rating": 3, "Comment": "Decent internet speeds.", "Department": "Electronics", "Year": "3rd Year", "Date": "2025-09-25" },
    { "Name": "Ishani Patel", "Facility": "Library", "Rating": 3, "Comment": "Average labs.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-08-29" },
    { "Name": "Tanvi Verma", "Facility": "CSE Lab", "Rating": 4, "Comment": "Sports center is well maintained.", "Department": "Civil Eng", "Year": "2nd Year", "Date": "2025-08-02" },
    { "Name": "Amit Gupta", "Facility": "Auditorium", "Rating": 3, "Comment": "Average labs.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-11-07" },
    { "Name": "Manish Verma", "Facility": "Auditorium", "Rating": 3, "Comment": "Could be better.", "Department": "Electronics", "Year": "1st Year", "Date": "2025-11-14" },
    { "Name": "Karthik Rao", "Facility": "Sports Center", "Rating": 3, "Comment": "Average experience at the cafeteria.", "Department": "Information Tech", "Year": "3rd Year", "Date": "2025-09-29" },
    { "Name": "Arjun Verma", "Facility": "Cafeteria", "Rating": 2, "Comment": "Wait times at cafeteria are too high.", "Department": "Electronics", "Year": "1st Year", "Date": "2025-10-25" },
    { "Name": "Abhishek Rao", "Facility": "IT Center", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Mechanical Eng", "Year": "1st Year", "Date": "2025-11-08" },
    { "Name": "Manish Gupta", "Facility": "Auditorium", "Rating": 3, "Comment": "Average experience at the cafeteria.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-10" },
    { "Name": "Arjun Singh", "Facility": "Library", "Rating": 5, "Comment": "Library has a great collection of research papers.", "Department": "Information Tech", "Year": "4th Year", "Date": "2025-12-20" },
    { "Name": "Sanjay Singh", "Facility": "IT Center", "Rating": 5, "Comment": "Library has a great collection of research papers.", "Department": "Electronics", "Year": "1st Year", "Date": "2025-11-20" },
    { "Name": "Neha Gupta", "Facility": "CSE Lab", "Rating": 3, "Comment": "Average experience at the cafeteria.", "Department": "Mechanical Eng", "Year": "2nd Year", "Date": "2025-12-19" },
    { "Name": "Amit Chauhan", "Facility": "Library", "Rating": 5, "Comment": "Excellent coding environment in labs.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-09-12" },
    { "Name": "Abhishek Gupta", "Facility": "Auditorium", "Rating": 3, "Comment": "Average labs.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-10-17" },
    { "Name": "Divya Singh", "Facility": "Cafeteria", "Rating": 1, "Comment": "Sports equipment is getting old.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-08-10" },
    { "Name": "Ritu Gupta", "Facility": "Sports Center", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Civil Eng", "Year": "1st Year", "Date": "2025-12-14" },
    { "Name": "Sanjay Verma", "Facility": "CSE Lab", "Rating": 5, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Civil Eng", "Year": "2nd Year", "Date": "2025-11-30" },
    { "Name": "Vikram Rao", "Facility": "IT Center", "Rating": 4, "Comment": "Library has a great collection of research papers.", "Department": "Business Admin", "Year": "4th Year", "Date": "2025-11-19" },
    { "Name": "Amit Verma", "Facility": "Cafeteria", "Rating": 3, "Comment": "Sports center gets a bit crowded.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-26" },
    { "Name": "Abhishek Patel", "Facility": "CSE Lab", "Rating": 4, "Comment": "CSE Lab equipment is top notch.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-11-05" },
    { "Name": "Arjun Nair", "Facility": "Auditorium", "Rating": 4, "Comment": "Excellent coding environment in labs.", "Department": "Mechanical Eng", "Year": "2nd Year", "Date": "2025-11-18" },
    { "Name": "Rahul Sharma", "Facility": "IT Center", "Rating": 4, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Mechanical Eng", "Year": "1st Year", "Date": "2025-12-03" },
    { "Name": "Kavya Singh", "Facility": "IT Center", "Rating": 4, "Comment": "CSE Lab equipment is top notch.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-08-02" },
    { "Name": "Karthik Verma", "Facility": "IT Center", "Rating": 2, "Comment": "Very noisy study environment.", "Department": "Business Admin", "Year": "4th Year", "Date": "2025-11-15" },
    { "Name": "Rohan Rao", "Facility": "IT Center", "Rating": 3, "Comment": "Sports center gets a bit crowded.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-09-11" },
    { "Name": "Ishani Iyer", "Facility": "IT Center", "Rating": 5, "Comment": "CSE Lab equipment is top notch.", "Department": "Business Admin", "Year": "1st Year", "Date": "2025-11-13" },
    { "Name": "Aditi Singh", "Facility": "Library", "Rating": 5, "Comment": "CSE Lab equipment is top notch.", "Department": "Information Tech", "Year": "1st Year", "Date": "2025-09-08" },
    { "Name": "Amit Chauhan", "Facility": "Cafeteria", "Rating": 2, "Comment": "Wait times at cafeteria are too high.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-11-23" },
    { "Name": "Suresh Rao", "Facility": "Auditorium", "Rating": 4, "Comment": "High-speed internet is a life saver.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-10-30" },
    { "Name": "Amit Nair", "Facility": "Sports Center", "Rating": 3, "Comment": "Average labs.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-09-21" },
    { "Name": "Abhishek Iyer", "Facility": "IT Center", "Rating": 3, "Comment": "Average labs.", "Department": "Electronics", "Year": "1st Year", "Date": "2025-10-26" },
    { "Name": "Priya Nair", "Facility": "Library", "Rating": 5, "Comment": "Library has a great collection of research papers.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-08-17" },
    { "Name": "Ritu Singh", "Facility": "IT Center", "Rating": 4, "Comment": "Excellent coding environment in labs.", "Department": "Business Admin", "Year": "3rd Year", "Date": "2025-11-08" },
    { "Name": "Rahul Verma", "Facility": "CSE Lab", "Rating": 5, "Comment": "CSE Lab equipment is top notch.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-08-05" },
    { "Name": "Ritu Iyer", "Facility": "CSE Lab", "Rating": 4, "Comment": "High-speed internet is a life saver.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-11-09" },
    { "Name": "Divya Patel", "Facility": "Cafeteria", "Rating": 1, "Comment": "Library needs more books for our branch.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-13" },
    { "Name": "Divya Chauhan", "Facility": "IT Center", "Rating": 3, "Comment": "Sports center gets a bit crowded.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-08-05" },
    { "Name": "Priya Sharma", "Facility": "CSE Lab", "Rating": 5, "Comment": "Library has a great collection of research papers.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-10-06" },
    { "Name": "Tanvi Rao", "Facility": "Library", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-11-03" },
    { "Name": "Arjun Sharma", "Facility": "CSE Lab", "Rating": 5, "Comment": "Sports center is well maintained.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-12" },
    { "Name": "Rohan Nair", "Facility": "Cafeteria", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-08-28" },
    { "Name": "Sanjay Chauhan", "Facility": "IT Center", "Rating": 3, "Comment": "Average labs.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-12-06" },
    { "Name": "Neha Gupta", "Facility": "CSE Lab", "Rating": 4, "Comment": "Excellent coding environment in labs.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-10-03" },
    { "Name": "Sonal Reddy", "Facility": "Cafeteria", "Rating": 1, "Comment": "Wait times at cafeteria are too high.", "Department": "Information Tech", "Year": "1st Year", "Date": "2025-12-01" },
    { "Name": "Anjali Nair", "Facility": "Auditorium", "Rating": 5, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-11-24" },
    { "Name": "Arjun Singh", "Facility": "CSE Lab", "Rating": 4, "Comment": "Library has a great collection of research papers.", "Department": "Electronics", "Year": "1st Year", "Date": "2025-09-07" },
    { "Name": "Ishani Reddy", "Facility": "CSE Lab", "Rating": 4, "Comment": "CSE Lab equipment is top notch.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-11-17" },
    { "Name": "Tanvi Rao", "Facility": "Library", "Rating": 5, "Comment": "Excellent coding environment in labs.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-10" },
    { "Name": "Priya Reddy", "Facility": "Sports Center", "Rating": 3, "Comment": "Library could be quieter.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-10-08" },
    { "Name": "Divya Patel", "Facility": "IT Center", "Rating": 2, "Comment": "Library needs more books for our branch.", "Department": "Information Tech", "Year": "2nd Year", "Date": "2025-08-09" },
    { "Name": "Karthik Nair", "Facility": "Auditorium", "Rating": 5, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Mechanical Eng", "Year": "3rd Year", "Date": "2025-09-01" },
    { "Name": "Sonal Rao", "Facility": "Sports Center", "Rating": 3, "Comment": "Average experience at the cafeteria.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-10-02" },
    { "Name": "Anjali Rao", "Facility": "Cafeteria", "Rating": 4, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-12-28" },
    { "Name": "Rohan Chauhan", "Facility": "Sports Center", "Rating": 4, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-11-24" },
    { "Name": "Abhishek Reddy", "Facility": "Cafeteria", "Rating": 2, "Comment": "AC in the CSE lab was leaking.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-08-02" },
    { "Name": "Karthik Verma", "Facility": "IT Center", "Rating": 3, "Comment": "Sports center gets a bit crowded.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-12-06" },
    { "Name": "Anjali Nair", "Facility": "Library", "Rating": 5, "Comment": "CSE Lab equipment is top notch.", "Department": "Civil Eng", "Year": "4th Year", "Date": "2025-12-21" },
    { "Name": "Sonal Rao", "Facility": "Auditorium", "Rating": 2, "Comment": "Very noisy study environment.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-10-22" },
    { "Name": "Ritu Iyer", "Facility": "Sports Center", "Rating": 4, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-10-01" },
    { "Name": "Anjali Iyer", "Facility": "CSE Lab", "Rating": 5, "Comment": "High-speed internet is a life saver.", "Department": "Civil Eng", "Year": "3rd Year", "Date": "2025-11-05" },
    { "Name": "Manish Gupta", "Facility": "Auditorium", "Rating": 4, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Business Admin", "Year": "3rd Year", "Date": "2025-09-27" },
    { "Name": "Aditi Chauhan", "Facility": "Cafeteria", "Rating": 2, "Comment": "AC in the CSE lab was leaking.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-11-24" },
    { "Name": "Kavya Singh", "Facility": "Library", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-11-11" },
    { "Name": "Suresh Iyer", "Facility": "Sports Center", "Rating": 5, "Comment": "Excellent coding environment in labs.", "Department": "Electronics", "Year": "3rd Year", "Date": "2025-12-24" },
    { "Name": "Kavya Gupta", "Facility": "Sports Center", "Rating": 4, "Comment": "Sports center is well maintained.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-06" },
    { "Name": "Amit Nair", "Facility": "CSE Lab", "Rating": 4, "Comment": "Library has a great collection of research papers.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-05" },
    { "Name": "Sanjay Patel", "Facility": "Library", "Rating": 2, "Comment": "Sports equipment is getting old.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-12-12" },
    { "Name": "Vikram Chauhan", "Facility": "Cafeteria", "Rating": 2, "Comment": "Sports equipment is getting old.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-11-30" },
    { "Name": "Manish Patel", "Facility": "CSE Lab", "Rating": 5, "Comment": "Excellent coding environment in labs.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-09-14" },
    { "Name": "Amit Gupta", "Facility": "Sports Center", "Rating": 3, "Comment": "Average labs.", "Department": "Information Tech", "Year": "1st Year", "Date": "2025-12-16" },
    { "Name": "Ishani Verma", "Facility": "Library", "Rating": 2, "Comment": "Library needs more books for our branch.", "Department": "Civil Eng", "Year": "1st Year", "Date": "2025-09-30" },
    { "Name": "Tanvi Chauhan", "Facility": "Auditorium", "Rating": 5, "Comment": "High-speed internet is a life saver.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-10-05" },
    { "Name": "Rohan Rao", "Facility": "CSE Lab", "Rating": 5, "Comment": "CSE Lab equipment is top notch.", "Department": "Business Admin", "Year": "3rd Year", "Date": "2025-11-23" },
    { "Name": "Priya Patel", "Facility": "IT Center", "Rating": 2, "Comment": "Wait times at cafeteria are too high.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-08-21" },
    { "Name": "Manish Gupta", "Facility": "Library", "Rating": 3, "Comment": "Decent internet speeds.", "Department": "Information Tech", "Year": "2nd Year", "Date": "2025-08-05" },
    { "Name": "Tanvi Reddy", "Facility": "IT Center", "Rating": 4, "Comment": "High-speed internet is a life saver.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-10-04" },
    { "Name": "Priya Chauhan", "Facility": "IT Center", "Rating": 5, "Comment": "Excellent coding environment in labs.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-09-15" },
    { "Name": "Anjali Sharma", "Facility": "Library", "Rating": 4, "Comment": "Excellent coding environment in labs.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-12-11" },
    { "Name": "Ritu Iyer", "Facility": "Sports Center", "Rating": 2, "Comment": "Sports equipment is getting old.", "Department": "Information Tech", "Year": "3rd Year", "Date": "2025-08-05" },
    { "Name": "Rahul Iyer", "Facility": "IT Center", "Rating": 3, "Comment": "Average experience at the cafeteria.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-11-17" },
    { "Name": "Aditi Iyer", "Facility": "IT Center", "Rating": 2, "Comment": "Sports equipment is getting old.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-08-10" },
    { "Name": "Karthik Chauhan", "Facility": "Auditorium", "Rating": 4, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-09-11" },
    { "Name": "Aditi Patel", "Facility": "IT Center", "Rating": 4, "Comment": "Sports center is well maintained.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-10-14" },
    { "Name": "Ritu Chauhan", "Facility": "Sports Center", "Rating": 2, "Comment": "Library needs more books for our branch.", "Department": "Electronics", "Year": "3rd Year", "Date": "2025-08-22" },
    { "Name": "Priya Patel", "Facility": "IT Center", "Rating": 2, "Comment": "IT center support is slow.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-11-24" },
    { "Name": "Rahul Nair", "Facility": "Cafeteria", "Rating": 3, "Comment": "Average experience at the cafeteria.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-10-20" },
    { "Name": "Manish Reddy", "Facility": "CSE Lab", "Rating": 3, "Comment": "Could be better.", "Department": "Civil Eng", "Year": "3rd Year", "Date": "2025-08-09" },
    { "Name": "Rahul Sharma", "Facility": "Sports Center", "Rating": 4, "Comment": "Library has a great collection of research papers.", "Department": "Computer Science & Engineering", "Year": "1st Year", "Date": "2025-12-07" },
    { "Name": "Amit Verma", "Facility": "IT Center", "Rating": 4, "Comment": "CSE Lab equipment is top notch.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-11-25" },
    { "Name": "Sanjay Patel", "Facility": "IT Center", "Rating": 2, "Comment": "Very noisy study environment.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-09-04" },
    { "Name": "Suresh Chauhan", "Facility": "Library", "Rating": 4, "Comment": "Library has a great collection of research papers.", "Department": "Civil Eng", "Year": "1st Year", "Date": "2025-09-03" },
    { "Name": "Amit Reddy", "Facility": "Auditorium", "Rating": 5, "Comment": "Cafeteria food is surprisingly good today.", "Department": "Computer Science & Engineering", "Year": "3rd Year", "Date": "2025-10-11" },
    { "Name": "Ishani Nair", "Facility": "IT Center", "Rating": 2, "Comment": "Sports equipment is getting old.", "Department": "Computer Science & Engineering", "Year": "4th Year", "Date": "2025-10-24" },
    { "Name": "Sonal Verma", "Facility": "IT Center", "Rating": 3, "Comment": "Could be better.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-08-06" },
    { "Name": "Ishani Nair", "Facility": "CSE Lab", "Rating": 5, "Comment": "Excellent coding environment in labs.", "Department": "Computer Science & Engineering", "Year": "2nd Year", "Date": "2025-08-23" }
];
